build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file || true'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
