language: php
php:
- 5.6
- 7.0
- hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - dl

before_install: phpenv config-rm xdebug.ini || true

install: composer install --optimize-autoloader
script: vendor/bin/phpunit
