language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm

matrix:
  allow_failures:
  - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - dl

before_install: phpenv config-rm xdebug.ini || true

install:
 - composer install --optimize-autoloader

script: phpunit
