language: php
php:
- 7.1
- 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - dl

before_install: phpenv config-rm xdebug.ini || true

install:
 - composer install --optimize-autoloader

script: phpunit
